NumPy ==>> Numerical Python

pip install numpy to install numpy on terminal

! pip install numpy to install numpy directly on the notebook.

In [140]:
! pip install numpy

In [141]:
#check verion of numpy

import numpy

In [142]:
numpy.__version__

'1.21.5'

In [143]:
import numpy as np

In [144]:
np.__version__

'1.21.5'

upgrade numpy

pip install --upgrade numpy == "version"  #terminal

! pip install --upgrade numpy == "version" #directly from the jupyter notebook.

In [145]:
import array

In [146]:
a = array.array('i',[1, 2, 3])
print(a)

array('i', [1, 2, 3])


In [147]:
import array as arr

b = arr.array('d', [2, 4, 6, 7])
print(b)

array('d', [2.0, 4.0, 6.0, 7.0])


In [148]:
type(b)

array.array

Note: Array accepts only real numbers not strings.

In [149]:
import numpy as np

In [150]:
_1d = np.array([1, 2, 3, 4])
print(_1d)

[1 2 3 4]


In [151]:
_1d.shape

(4,)

In [152]:
_1d.ndim

1

In [153]:
l1 = ["cat", 'dog']
l2 = [1, 2]
l3 = l1 + l2
print(l3)

['cat', 'dog', 1, 2]


Adding arrays

In [154]:
a1 = np.array([1, 2, 4])
a2 = np.array([2, 3, 4])
a3 = a1 + a2
print(a3)

[3 5 8]


In [155]:
type(a3) #type 

numpy.ndarray

### Two dimensional array

- Matrices

Read more on matrices https://www.wikihow.com/Understand-the-Basics-of-Matrices

In [156]:
array_1 = np.array([[1, 2, 3],
[2, 3, 4]])
print(array_1)

[[1 2 3]
 [2 3 4]]


In [157]:
array_1 = np.array([[2, 4, 6],
[8, 10 , 10]])

array_2 = np.array([1, 3])

In [158]:
array_3 = array_1 + array_2

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [159]:
array_2.shape, array_1.shape, array_1.ndim

((2,), (2, 3), 2)

Note: The matrices must have the same dimensions before it can be added

In [160]:
array_3

array([[ 3,  7, 11],
       [ 9, 13, 15]])

In [161]:
array_1 = np.array([[2, 4, 6],
[8, 10 , 10]])

array_2 = np.array([1, 3, 5])

In [162]:
array_3 = array_1 + array_2
array_3

array([[ 3,  7, 11],
       [ 9, 13, 15]])

In [163]:
print(array_3)

[[ 3  7 11]
 [ 9 13 15]]


#### Array attributes

In [164]:
array_3.ndim #dimension

2

In [165]:
array_3.shape #2 * 3 matrices

(2, 3)

In [166]:
array_3.argmax()

5

In [167]:
array_3.max()

15

In [168]:
array_3.min()

3

In [169]:
array_3.argmin()

0

In [170]:
array_3.dtype 

dtype('int64')

In [171]:
type(array_3)

numpy.ndarray

In [172]:
array_3.all

<function ndarray.all>

In [173]:
array_3.shape

(2, 3)

In [174]:
array_3.reshape(3, 2)

array([[ 3,  7],
       [11,  9],
       [13, 15]])

In [175]:
array_3.reshape(-1, 1)

array([[ 3],
       [ 7],
       [11],
       [ 9],
       [13],
       [15]])

In [176]:
array_3.reshape(6, 1)

array([[ 3],
       [ 7],
       [11],
       [ 9],
       [13],
       [15]])

In [177]:
array_3.reshape(-1, 1)

array([[ 3],
       [ 7],
       [11],
       [ 9],
       [13],
       [15]])

In [178]:
array_4 = np.array([[1, 2],
[2, 3]])

In [179]:
array_4.shape

(2, 2)

In [180]:
array_4.reshape(-1, 1)

array([[1],
       [2],
       [2],
       [3]])

In [181]:
array_3

array([[ 3,  7, 11],
       [ 9, 13, 15]])

In [182]:
arr_T = array_3.T #transpose
print(arr_T)

[[ 3  9]
 [ 7 13]
 [11 15]]


In [183]:
array_3.shape, arr_T.shape

((2, 3), (3, 2))

In [184]:
arr_1 = np.array([1, 2, 4])
print(arr_1)

[1 2 4]


In [185]:
arr_2 = np.array([[2, 4, 6],
                 [8, 10, 12]])
print(arr_2)

[[ 2  4  6]
 [ 8 10 12]]


In [186]:
arr_3 = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]])
print(arr_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [187]:
arr_4 = np.array([[[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]]]])
print(arr_4)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


In [188]:
arr_1.ndim, arr_2.ndim, arr_3.ndim, arr_4.ndim

(1, 2, 3, 4)

In [189]:
# scalar multiplication of matrices
arr_1 = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]])

mul = 3* arr_1
print(mul)

[[[ 3  6  9]
  [12 15 18]
  [21 24 27]]]


In [190]:
# vector multiplication of a matrices
arr_1 = np.array([[1, 4, 7],
                 [2, 3, 5]])

arr_2 = np.array([[1, 2, 4],
                  [1, 2, 5]])

product = arr_1 * arr_2
print(product)

[[ 1  8 28]
 [ 2  6 25]]


In [191]:
# dot product of a matrices
arr_1

array([[1, 4, 7],
       [2, 3, 5]])

In [192]:
A = arr_1.dot(3)
A

array([[ 3, 12, 21],
       [ 6,  9, 15]])

In [193]:
B = arr_1 * 3
B

array([[ 3, 12, 21],
       [ 6,  9, 15]])

In [194]:
A == B

array([[ True,  True,  True],
       [ True,  True,  True]])

In [195]:
arr_1 == arr_2

array([[ True, False, False],
       [False, False,  True]])

#### Assessment

- Create an array of 1-dimension, 2-dimension, 3-dimension , and 4-dimension
- Using the numpy attribute to do the following: shape of each array, dimension, min, max, and argmax of each array.
- Perform basic math operation of array by creating to n-dimensional arrays.

In [196]:
for i in range(1, 10, 1):
    print(i, end = ' ')

1 2 3 4 5 6 7 8 9 

In [197]:
array_a = np.arange(1, 10, 1)
print(array_a)

[1 2 3 4 5 6 7 8 9]


In [198]:
type(array_a)

numpy.ndarray

In [199]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [200]:

#generate random numbers
np.random.seed(42) #always set a seed to avoid random changes in the values
a = np.random.random(size = 100)
print(a)


[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
 0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691
 0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802
 0.54671028 0.18485446 0.96958463 0.77513282 0.93949894 0.89482735
 0.59789998 0.92187424 0.0884925  0.19598286 0.04522729 0.32533033
 0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
 0.14092422 0.80219698 0.07455064 0.98688694 0.77224477 0.19871568
 0.00552212 0.81546143 0.70685734 0.72900717 0.77127035 0.07404465
 0.35846573 0.11586906 0.86310343 0.62329813 0.33089802 0.06355835
 0.31098232 0.32518332 0.72960618 0.63755747 0.88721274 0.4722

In [201]:
a.dtype

dtype('float64')

In [202]:
b = np.random.randn(12)
print(b)

[ 0.08704707 -0.29900735  0.09176078 -1.98756891 -0.21967189  0.35711257
  1.47789404 -0.51827022 -0.8084936  -0.50175704  0.91540212  0.32875111]


In [203]:
b.dtype

dtype('float64')

In [204]:
d = np.random.rand(12)
print(d)

[0.80367208 0.18657006 0.892559   0.53934224 0.80744016 0.8960913
 0.31800347 0.11005192 0.22793516 0.42710779 0.81801477 0.86073058]


In [205]:
np.linspace(-3, 3, 7)

array([-3., -2., -1.,  0.,  1.,  2.,  3.])

In [206]:
ones = np.ones(shape = (5, 5), dtype = "int64")
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [207]:
zeros = np.zeros(shape = (3,3), dtype = "float")
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [208]:
full = np.full(shape = (12, 5), fill_value = 12, dtype = "int64")
print(full)

[[12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]]


In [209]:
identity = np.eye(N = 3, M = 3, dtype = "int")
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Array Indexing/ slicing

- Reference List

In [210]:
li = [1, 2, 3, 4, 5]
print(li)

[1, 2, 3, 4, 5]


In [211]:
li[:]

[1, 2, 3, 4, 5]

In [212]:
li[:2]

[1, 2]

In [213]:
li[5]

IndexError: list index out of range

In [214]:
np.random.seed(42)
array_a = np.random.random(12)
print(array_a)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]


In [215]:
array_a[:]

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985])

In [216]:
array_a.ndim

1

In [217]:
array_a.shape

(12,)

In [218]:
array_a[:4]

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [219]:
array_b = np.array([[[1, 2, 4],
                    [2, 3, 5],
                    [8, 9, 10]]])

print(array_b)

[[[ 1  2  4]
  [ 2  3  5]
  [ 8  9 10]]]


In [220]:
array_b.ndim

3

In [221]:
array_b.shape

(1, 3, 3)

In [222]:
array_b[:, :] #the first column is for rows index, the second is for column index

array([[[ 1,  2,  4],
        [ 2,  3,  5],
        [ 8,  9, 10]]])

In [223]:
array_b[:, 2, 2]

array([10])

In [224]:
array_b[:, 0, :2]

array([[1, 2]])

### Array Transpose

In [225]:
array_b

array([[[ 1,  2,  4],
        [ 2,  3,  5],
        [ 8,  9, 10]]])

In [226]:
array_b.T

array([[[ 1],
        [ 2],
        [ 8]],

       [[ 2],
        [ 3],
        [ 9]],

       [[ 4],
        [ 5],
        [10]]])

In [227]:
c = np.array([[1, 2],
             [3, 4]])
print(c)

[[1 2]
 [3 4]]


In [228]:
c.T

array([[1, 3],
       [2, 4]])

### Universal Array Functions

In [229]:
type(c)

numpy.ndarray

In [230]:
array_a

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985])

In [231]:
array_b

array([[[ 1,  2,  4],
        [ 2,  3,  5],
        [ 8,  9, 10]]])

In [232]:
np.multiply(2, array_b)

array([[[ 2,  4,  8],
        [ 4,  6, 10],
        [16, 18, 20]]])

In [233]:
2 * array_b

array([[[ 2,  4,  8],
        [ 4,  6, 10],
        [16, 18, 20]]])

In [234]:
arr_1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr_2 = np.array([[[10, 11],
                  [20, 21],
                  [30, 31]]])

In [235]:
arr_1.shape, arr_2.shape

((2, 3), (1, 3, 2))

In [236]:
arr_3 = np.matmul(arr_1, arr_2)
arr_3

array([[[140, 146],
        [320, 335]]])

In [237]:
array_c = np.array([[1, 2],
                   [3, 4]])
array_d = np.array([[5, 6],
                   [8, 9]])

np.matmul(array_c, array_d)

array([[21, 24],
       [47, 54]])

In [238]:
array_c

array([[1, 2],
       [3, 4]])

In [239]:
array_d

array([[5, 6],
       [8, 9]])

In [240]:
array_c * array_d

array([[ 5, 12],
       [24, 36]])

In [241]:
li = [1, 2, 3, 5]
li

[1, 2, 3, 5]

In [242]:
type(li)

list

In [243]:
a_li = np.array(li)
a_li

array([1, 2, 3, 5])

In [244]:
type(a_li)

numpy.ndarray

Read more on NumPy docs https://numpy.org/doc/stable/reference/ufuncs.html