NumPy ==>> Numerical Python

pip install numpy to install numpy on terminal

! pip install numpy to install numpy directly on the notebook.

In [1]:
! pip install numpy

In [2]:
#check verion of numpy

import numpy

In [3]:
numpy.__version__

'1.21.5'

In [4]:
import numpy as np

In [5]:
np.__version__

'1.21.5'

upgrade numpy

pip install --upgrade numpy == "version"  #terminal

! pip install --upgrade numpy == "version" #directly from the jupyter notebook.

In [6]:
import array

In [10]:
a = array.array('i',[1, 2, 3])
print(a)

array('i', [1, 2, 3])


In [14]:
import array as arr

b = arr.array('d', [2, 4, 6, 7])
print(b)

array('d', [2.0, 4.0, 6.0, 7.0])


In [12]:
type(b)

array.array

Note: Array accepts only real numbers not strings.

In [15]:
import numpy as np

In [16]:
_1d = np.array([1, 2, 3, 4])
print(_1d)

[1 2 3 4]


In [17]:
_1d.shape

(4,)

In [18]:
_1d.ndim

1

In [19]:
l1 = ["cat", 'dog']
l2 = [1, 2]
l3 = l1 + l2
print(l3)

['cat', 'dog', 1, 2]


Adding arrays

In [20]:
a1 = np.array([1, 2, 4])
a2 = np.array([2, 3, 4])
a3 = a1 + a2
print(a3)

[3 5 8]


In [21]:
type(a3) #type 

numpy.ndarray

### Two dimensional array

- Matrices

Read more on matrices https://www.wikihow.com/Understand-the-Basics-of-Matrices

In [22]:
array_1 = np.array([[1, 2, 3],
[2, 3, 4]])
print(array_1)

[[1 2 3]
 [2 3 4]]


In [32]:
array_1 = np.array([[2, 4, 6],
[8, 10 , 10]])

array_2 = np.array([1, 3])

In [33]:
array_3 = array_1 + array_2

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [36]:
array_2.shape, array_1.shape, array_1.ndim

((2,), (2, 3), 2)

Note: The matrices must have the same dimensions before it can be added

In [37]:
array_3

array([[ 3,  7, 11],
       [ 9, 13, 15]])

In [38]:
array_1 = np.array([[2, 4, 6],
[8, 10 , 10]])

array_2 = np.array([1, 3, 5])

In [39]:
array_3 = array_1 + array_2
array_3

array([[ 3,  7, 11],
       [ 9, 13, 15]])

In [40]:
print(array_3)

[[ 3  7 11]
 [ 9 13 15]]


#### Array attributes

In [41]:
array_3.ndim #dimension

2

In [42]:
array_3.shape #2 * 3 matrices

(2, 3)

In [43]:
array_3.argmax()

5

In [44]:
array_3.max()

15

In [45]:
array_3.min()

3

In [46]:
array_3.argmin()

0

In [47]:
array_3.dtype 

dtype('int64')

In [48]:
type(array_3)

numpy.ndarray

In [49]:
array_3.all

<function ndarray.all>

In [50]:
array_3.shape

(2, 3)

In [51]:
array_3.reshape(3, 2)

array([[ 3,  7],
       [11,  9],
       [13, 15]])

In [52]:
array_3.reshape(-1, 1)

array([[ 3],
       [ 7],
       [11],
       [ 9],
       [13],
       [15]])

In [54]:
array_3.reshape(6, 1)

array([[ 3],
       [ 7],
       [11],
       [ 9],
       [13],
       [15]])

In [66]:
array_3.reshape(-1, 1)

array([[ 3],
       [ 7],
       [11],
       [ 9],
       [13],
       [15]])

In [70]:
array_4 = np.array([[1, 2],
[2, 3]])

In [71]:
array_4.shape

(2, 2)

In [74]:
array_4.reshape(-1, 1)

array([[1],
       [2],
       [2],
       [3]])

In [75]:
array_3

array([[ 3,  7, 11],
       [ 9, 13, 15]])

In [76]:
arr_T = array_3.T #transpose
print(arr_T)

[[ 3  9]
 [ 7 13]
 [11 15]]


In [78]:
array_3.shape, arr_T.shape

((2, 3), (3, 2))

In [79]:
arr_1 = np.array([1, 2, 4])
print(arr_1)

[1 2 4]


In [80]:
arr_2 = np.array([[2, 4, 6],
                 [8, 10, 12]])
print(arr_2)

[[ 2  4  6]
 [ 8 10 12]]


In [81]:
arr_3 = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]])
print(arr_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [82]:
arr_4 = np.array([[[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]]]])
print(arr_4)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


In [83]:
arr_1.ndim, arr_2.ndim, arr_3.ndim, arr_4.ndim

(1, 2, 3, 4)

In [84]:
# scalar multiplication of matrices
arr_1 = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]])

mul = 3* arr_1
print(mul)

[[[ 3  6  9]
  [12 15 18]
  [21 24 27]]]


In [85]:
# vector multiplication of a matrices
arr_1 = np.array([[1, 4, 7],
                 [2, 3, 5]])

arr_2 = np.array([[1, 2, 4],
                  [1, 2, 5]])

product = arr_1 * arr_2
print(product)

[[ 1  8 28]
 [ 2  6 25]]


In [86]:
# dot product of a matrices
arr_1

array([[1, 4, 7],
       [2, 3, 5]])

In [87]:
A = arr_1.dot(3)
A

array([[ 3, 12, 21],
       [ 6,  9, 15]])

In [88]:
B = arr_1 * 3
B

array([[ 3, 12, 21],
       [ 6,  9, 15]])

In [89]:
A == B

array([[ True,  True,  True],
       [ True,  True,  True]])

In [90]:
arr_1 == arr_2

array([[ True, False, False],
       [False, False,  True]])